from enum import Enum


class EventType(str, Enum):
    REGISTRATION = "REGISTRATION"
    TRIAGE = "TRIAGE"
    BED_ASSIGNMENT = "BED_ASSIGNMENT"
    TREATMENT = "TREATMENT"
    DISPOSITION = "DISPOSITION"
    DEPARTURE = "DEPARTURE"


class Disposition(str, Enum):
    DISCHARGED = "DISCHARGED"
    ADMITTED = "ADMITTED"
    TRANSFERRED = "TRANSFERRED"
    LEFT_WITHOUT_TREATMENT = "LEFT_WITHOUT_TREATMENT"
